//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileId { get; set; }
        public string FileName { get; set; }
        public System.DateTime UploadDate { get; set; }
        public Nullable<int> ThesisId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Thesis Thesis { get; set; }
        public virtual Project Project { get; set; }
    }
}
