//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Files = new HashSet<File>();
        }
    
        public int ProjectId { get; set; }
        public Nullable<double> Note { get; set; }
        public string Review { get; set; }
        public string Scope { get; set; }
        public string Goal { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public bool IsReviewed { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Title { get; set; }
        public int ClassId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual Class Class { get; set; }
    }
}
